### ISSUE TITLE
What computer software does this project use to operate and display waveforms?

### ISSUE THREAD

**Issue by xykts** [arisberd/Infant-breath-mechanical-simulator#2]
hi,dear.author

What computer software does this project use to operate and display waveforms?
I saw in the project video that there is computer software that can display waveform and operation

What computer software can it use   。

**Comment by arisberd** [comment]
Hi @xykts 

This project is still developing. The input data are given as csv values.

In this prototyping video you saw, we are checking the accuracy using commercial software and hardware, which is Smartlab and Insight. Using a pneumotachograph we calibrate and validate the accuracy of the simulator.

https://www.rudolphkc.com/product-page/smartlab-data-acquisition-system

I hope I help

**Comment by xykts** [comment]
OK, look forward to new results
